---
title: "assignment5"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{assignment5}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(conflicted)
library(tidyverse)
library(testthat, warn.conflicts = FALSE)
library(assertive, warn.conflicts = FALSE)
library(raster, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
library(geospaar, warn.conflicts = FALSE)
library(rgeos, warn.conflicts = FALSE)
library(rgdal, warn.conflicts = FALSE)
library(gstat, warn.conflicts = FALSE)
library(git2r, warn.conflicts = FALSE)
library(sf, warn.conflicts = FALSE)
#1 load in data and libraries
farmers <- system.file("extdata/farmer_spatial.csv", package = "geospaar") %>%   
  read_csv() 
districts <- system.file("extdata/districts.shp", package = "geospaar") %>% 
  st_read
roads <- system.file("extdata/roads.shp", package = "geospaar") %>% st_read
#1
#Luke Watson-Sharer
districts_ss <- districts %>% slice(c(22, 26, 53, 54))
districts_ss

r <- raster(x = districts_ss, res = 0.1, crs = crs(districts))
r

rsamp <- r
set.seed(1)  
values(rsamp) <- sample(1:50, ncell(rsamp), replace = TRUE)
rsamp

runi <- r
set.seed(1)
values(runi) <-  rnorm(ncell(runi), mean = 30, sd = 5)
runi

stack_1 <- stack(c(runi, rsamp))
plot(stack_1)
mask_1 <- mask(x = stack_1, mask = districts)
par(mar = c(0, 0, 0, 4))
plot_noaxes(mask_1, box = FALSE)

stack_1 <- stack(c(runi, rsamp))
plot(stack_1)
mask_1 <- mask(x = stack_1, mask = districts_ss)
par(mar = c(0, 0, 0, 4))
plot_noaxes(mask_1, box = FALSE)

```

```{r}
#2
s2_1d <- disaggregate(x = stack_1[[1]], fact = 4, method = "bilinear")
s2_1d
#Disaggreagte result
s2_1gt35 <- (s2_1d > 35) %>% plot()
s2_1gt35[s2_1d == 0] <- NA
s2_1gt35
# new raster
s2poly <- rasterToPolygons(x = s2_1gt35, dissolve = TRUE) %>% st_as_sf
s2poly %>% plot()
#new sf object and plotting it
```

```{r} 
#dix mask and review
#3
zamr <- raster(x = extent(districts), crs = crs(districts), res = 0.5)
values(zamr) <- 1
# new grid
farmersr <- farmers %>% distinct(uuid, .keep_all = TRUE) %>% 
  dplyr::select(x, y) %>% mutate(count = 1) %>% 
  st_as_sf(coords = c("x", "y"), crs = 4326) %>% 
  rasterize(x = ., y = zamr, field = "count", fun = sum) %>% print()
# recreated daatase summing farmers
par(mar = c(0, 0, 1, 4))
districts %>% st_union %>% 
  plot(col = "grey", border = "grey", 
       main = expression(paste("N farmers per 0.25", degree, " cell")))
mask_2 <- mask(x = farmersr, mask = districts)
plot(mask_2, add = TRUE)
```

```{r}
#4
farmerspts <- rasterToPoints(x = farmersr, spatial = TRUE) %>% st_as_sf
zamr2 <- raster(x = extent(districts), crs = crs(districts), res = 0.05)
zamr2

set.seed(1)
dist1 <- distanceFromPoints(object = zamr2, xy = as_Spatial(farmerspts))
dist1
plot(dist1)
dist_to_farmers_temp <- mask(x = dist1, mask = districts)
dist_to_farmers <- dist_to_farmers_temp/1000
plot_noaxes(dist_to_farmers)
plot(farmerspts, add = T)
```

```{r}
#5
wctmean <- getData("worldclim", var = "tmean", res = 2.5,
path = tempdir())
zamtmean <- crop(wctmean, y = districts) 
zamtmean <- mask(calc(zamtmean, mean), mask = districts)
zamtmean <- (zamtmean / 10)
plot(zamtmean)
```

```{r}
#6
trng <- cellStats(zamtmean, range)
trng

reclmat <- cbind(c(floor(trng[1]), 20, 24), c(20, 24, ceiling(trng[2])), 1:3)
zamtclass <- reclassify(x = zamtmean, rcl = reclmat, include.lowest = TRUE)

plot_noaxes(zamtclass, legend = FALSE, col =c("blue", "yellow2", "red"), mar =c(0, 0, 1, 0))

legend(x = "bottomright", legend = c("Low", "Intermediate", "High"), 
       col = c("blue", "yellow2", "red"), pch = 15, pt.cex =3)
#What are the functions floor and ceiling doing 


```

```{r}
#7
data(zamprec)
z1 <- zonal(x = zamprec, z = zamtclass, fun = "mean", na.rm = "TRUE")
z2 <- as.data.frame(z1) #convert matrix to data frame
plot(z1)
zamprecz <- z2 %>% data.frame %>% subs(x = zamtclass, y = ., by = "zone")
plot_noaxes(zamprecz, legend = FALSE, col = c("yellow2", "green3", "blue"), mar = c(0, 0, 1, 0))
legend(x = "bottomright", legend = round(z2$mean), pch = 15, pt.cex =3, col = c("yellow2", "green3", "blue"))
```

```{r}
#8
dem <- getData(name = "alt", country = "ZMB", path = tempdir())
dem5 <- aggregate(x = dem, fact = 5)
plot(dem5)
aspect <- terrain(x = dem5, opt = 'aspect', unit = 'degrees') 
plot(aspect)
west <- aspect > 247.5 & aspect < 292.5
east <- aspect > 67.5 & aspect < 112.5
east_west <- stack(aspect, west, east)
titles <- c("Aspect", "West", "East")
plot_noaxes(east_west, main = titles)
```

```{r}
#9
west[west == 0] <- NA
set.seed(1)
westpts <- sampleRandom(x = west, size = 100, na.rm = TRUE, sp = TRUE) %>% st_as_sf 
east[east == 0] <- NA
set.seed(1)
eastpts <- sampleRandom(x = east, size = 100, na.rm = TRUE, sp = TRUE) %>% st_as_sf
temp_stats <- bind_rows( tibble(temp = raster::extract(zamtmean, westpts), dat = "West"), tibble(temp = raster::extract(zamtmean, eastpts), dat = "East"))
```

```{r}
#10
dcent <- st_centroid(districts)
dcent_alb <- st_transform(dcent, st_crs(roads))
dcent_alb
zamtmeanalb <- projectRaster(from = zamtmean,  res = 5000 , crs = crs(roads),  method="bilinear")
temp <- raster::extract(zamtmeanalb, dcent_alb)
dcent_alb <- dcent_alb %>% mutate(temp = temp)
dcent <- bind_cols(
  dcent %>% data.frame %>% dplyr::select(-geometry) %>% as_tibble, 
  st_coordinates(dcent) %>% as_tibble
) %>% rename(x = X, y = Y)
idw <- gstat(id = "temp", formula = temp ~ 1, locations = ~x + y, 
                 data = dcent)
idwinterpolate <- interpolate(object = r, model = idw)
ex= extent(idwinterpolate)
ex_2 =crop(zamtmeanalb, ex )
idwinterpolate_2 <- mask(x = ex , mask = zamtmeanalb)
plot(zamtmeanalb)
plot(dcentalb)
#not complete

```
